
/*******************************************************************************
 * automatically generated by Resx2Js.exe
 *******************************************************************************/
using System.Runtime.CompilerServices;

namespace MultiSelectionCalendar
{
	public class MultiSelectionCalendarResource
	{
		#region private

		[InlineCode("typeof global.MultiSelectionCalendar.Strings[{isoCode}]!= \"undefined\"")]
		private static bool ExistLanguage(string isoCode)
		{
			return false;
		}

		[InlineCode("global.MultiSelectionCalendar.Strings[{isoCode}][{key}]")]
		private static string GetStringInternal(string isoCode, string key)
		{
			return null;
		}

		private static string GetString(string key)
		{
			if (ExistLanguage(CurrentLanguageIsoCode))
			{
				var text = GetStringInternal(CurrentLanguageIsoCode, key);
				if (text != null)
					return text;
			}

			var txt = GetStringInternal("default", key);
			return txt;
		}

		#endregion

		#region public

		/// <summary>
		/// Sets the current language as ISO code
		/// e.g.: "de", "en", ""(default)
		/// </summary>
		public static string CurrentLanguageIsoCode { get; set; }

		#region Keys

		
		public static string April { get { return GetString("april"); } }
		public static string August { get { return GetString("august"); } }
		public static string December { get { return GetString("december"); } }
		public static string February { get { return GetString("february"); } }
		public static string Friday { get { return GetString("friday"); } }
		public static string HintNextMonth { get { return GetString("hintnextmonth"); } }
		public static string HintPreviousMonth { get { return GetString("hintpreviousmonth"); } }
		public static string January { get { return GetString("january"); } }
		public static string July { get { return GetString("july"); } }
		public static string June { get { return GetString("june"); } }
		public static string March { get { return GetString("march"); } }
		public static string May { get { return GetString("may"); } }
		public static string Monday { get { return GetString("monday"); } }
		public static string November { get { return GetString("november"); } }
		public static string October { get { return GetString("october"); } }
		public static string Saturday { get { return GetString("saturday"); } }
		public static string September { get { return GetString("september"); } }
		public static string Sunday { get { return GetString("sunday"); } }
		public static string Thursday { get { return GetString("thursday"); } }
		public static string Tuesday { get { return GetString("tuesday"); } }
		public static string Wednesday { get { return GetString("wednesday"); } }


		#endregion

		#endregion
	}
}